package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 12:21:18 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhrHmoTrxHdr_EOImpl extends EntityImpl {

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        this.setApprovalStatus("DRAFT");
        super.create(attributeList);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HmoTrxHdrId,
        BusinessUnitId,
        HmoRequestNo,
        HmoRequestDate,
        HmoMasterHdrId,
        HmoType,
        PersonId,
        MobileNo,
        MaritalStatus,
        ResiAddress,
        HmoCategory,
        HmoOption,
        HmoPlanTotal,
        HmoPlanDeduction,
        HmoAcceptanceFlag,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        EmpName_Trans,
        EmpNumber_Trans,
        BusinessUnit_Trans,
        Email_Trans,
        DeptName_Trans,
        Gender,
        Hospital,
        Photo,
        StateOfResidence,
        AlternateEmail,
        PhotoClob,
        HmoCopyDepFlag,
        AddiCategory,
        SoaFlowid,
        PayrollBatchName,
        ErrorMsg,
        ApproverComments,
        ApprovalStatus,
        CopyDep,
        HmoPlan,
        HmoEmpCost,
        XxhrHmoTrxDtl_EO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HMOTRXHDRID = AttributesEnum.HmoTrxHdrId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int HMOREQUESTNO = AttributesEnum.HmoRequestNo.index();
    public static final int HMOREQUESTDATE = AttributesEnum.HmoRequestDate.index();
    public static final int HMOMASTERHDRID = AttributesEnum.HmoMasterHdrId.index();
    public static final int HMOTYPE = AttributesEnum.HmoType.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int MARITALSTATUS = AttributesEnum.MaritalStatus.index();
    public static final int RESIADDRESS = AttributesEnum.ResiAddress.index();
    public static final int HMOCATEGORY = AttributesEnum.HmoCategory.index();
    public static final int HMOOPTION = AttributesEnum.HmoOption.index();
    public static final int HMOPLANTOTAL = AttributesEnum.HmoPlanTotal.index();
    public static final int HMOPLANDEDUCTION = AttributesEnum.HmoPlanDeduction.index();
    public static final int HMOACCEPTANCEFLAG = AttributesEnum.HmoAcceptanceFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int EMPNAME_TRANS = AttributesEnum.EmpName_Trans.index();
    public static final int EMPNUMBER_TRANS = AttributesEnum.EmpNumber_Trans.index();
    public static final int BUSINESSUNIT_TRANS = AttributesEnum.BusinessUnit_Trans.index();
    public static final int EMAIL_TRANS = AttributesEnum.Email_Trans.index();
    public static final int DEPTNAME_TRANS = AttributesEnum.DeptName_Trans.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int HOSPITAL = AttributesEnum.Hospital.index();
    public static final int PHOTO = AttributesEnum.Photo.index();
    public static final int STATEOFRESIDENCE = AttributesEnum.StateOfResidence.index();
    public static final int ALTERNATEEMAIL = AttributesEnum.AlternateEmail.index();
    public static final int PHOTOCLOB = AttributesEnum.PhotoClob.index();
    public static final int HMOCOPYDEPFLAG = AttributesEnum.HmoCopyDepFlag.index();
    public static final int ADDICATEGORY = AttributesEnum.AddiCategory.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int COPYDEP = AttributesEnum.CopyDep.index();
    public static final int HMOPLAN = AttributesEnum.HmoPlan.index();
    public static final int HMOEMPCOST = AttributesEnum.HmoEmpCost.index();
    public static final int XXHRHMOTRXDTL_EO = AttributesEnum.XxhrHmoTrxDtl_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhrHmoTrxHdr_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.XxhrHmoTrxHdr_EO");
    }


    /**
     * Gets the attribute value for HmoTrxHdrId, using the alias name HmoTrxHdrId.
     * @return the value of HmoTrxHdrId
     */
    public Number getHmoTrxHdrId() {
        return (Number) getAttributeInternal(HMOTRXHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoTrxHdrId.
     * @param value value to set the HmoTrxHdrId
     */
    public void setHmoTrxHdrId(Number value) {
        setAttributeInternal(HMOTRXHDRID, value);
    }

    /**
     * Gets the attribute value for BusinessUnitId, using the alias name BusinessUnitId.
     * @return the value of BusinessUnitId
     */
    public Number getBusinessUnitId() {
        return (Number) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnitId.
     * @param value value to set the BusinessUnitId
     */
    public void setBusinessUnitId(Number value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for HmoRequestNo, using the alias name HmoRequestNo.
     * @return the value of HmoRequestNo
     */
    public String getHmoRequestNo() {
        return (String) getAttributeInternal(HMOREQUESTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoRequestNo.
     * @param value value to set the HmoRequestNo
     */
    public void setHmoRequestNo(String value) {
        setAttributeInternal(HMOREQUESTNO, value);
    }

    /**
     * Gets the attribute value for HmoRequestDate, using the alias name HmoRequestDate.
     * @return the value of HmoRequestDate
     */
    public Timestamp getHmoRequestDate() {
        return (Timestamp) getAttributeInternal(HMOREQUESTDATE);
    }

    /**
     * Gets the attribute value for HmoMasterHdrId, using the alias name HmoMasterHdrId.
     * @return the value of HmoMasterHdrId
     */
    public Number getHmoMasterHdrId() {
        return (Number) getAttributeInternal(HMOMASTERHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoMasterHdrId.
     * @param value value to set the HmoMasterHdrId
     */
    public void setHmoMasterHdrId(Number value) {
        setAttributeInternal(HMOMASTERHDRID, value);
    }

    /**
     * Gets the attribute value for HmoType, using the alias name HmoType.
     * @return the value of HmoType
     */
    public String getHmoType() {
        return (String) getAttributeInternal(HMOTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoType.
     * @param value value to set the HmoType
     */
    public void setHmoType(String value) {
        setAttributeInternal(HMOTYPE, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the value of MobileNo
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for MaritalStatus, using the alias name MaritalStatus.
     * @return the value of MaritalStatus
     */
    public String getMaritalStatus() {
        return (String) getAttributeInternal(MARITALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaritalStatus.
     * @param value value to set the MaritalStatus
     */
    public void setMaritalStatus(String value) {
        setAttributeInternal(MARITALSTATUS, value);
    }

    /**
     * Gets the attribute value for ResiAddress, using the alias name ResiAddress.
     * @return the value of ResiAddress
     */
    public String getResiAddress() {
        return (String) getAttributeInternal(RESIADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResiAddress.
     * @param value value to set the ResiAddress
     */
    public void setResiAddress(String value) {
        setAttributeInternal(RESIADDRESS, value);
    }

    /**
     * Gets the attribute value for HmoCategory, using the alias name HmoCategory.
     * @return the value of HmoCategory
     */
    public String getHmoCategory() {
        return (String) getAttributeInternal(HMOCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoCategory.
     * @param value value to set the HmoCategory
     */
    public void setHmoCategory(String value) {
        setAttributeInternal(HMOCATEGORY, value);
    }

    /**
     * Gets the attribute value for HmoOption, using the alias name HmoOption.
     * @return the value of HmoOption
     */
    public String getHmoOption() {
        return (String) getAttributeInternal(HMOOPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoOption.
     * @param value value to set the HmoOption
     */
    public void setHmoOption(String value) {
        setAttributeInternal(HMOOPTION, value);
    }

    /**
     * Gets the attribute value for HmoPlanTotal, using the alias name HmoPlanTotal.
     * @return the value of HmoPlanTotal
     */
    public BigDecimal getHmoPlanTotal() {
        return (BigDecimal) getAttributeInternal(HMOPLANTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoPlanTotal.
     * @param value value to set the HmoPlanTotal
     */
    public void setHmoPlanTotal(BigDecimal value) {
        setAttributeInternal(HMOPLANTOTAL, value);
    }

    /**
     * Gets the attribute value for HmoPlanDeduction, using the alias name HmoPlanDeduction.
     * @return the value of HmoPlanDeduction
     */
    public BigDecimal getHmoPlanDeduction() {
        return (BigDecimal) getAttributeInternal(HMOPLANDEDUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoPlanDeduction.
     * @param value value to set the HmoPlanDeduction
     */
    public void setHmoPlanDeduction(BigDecimal value) {
        setAttributeInternal(HMOPLANDEDUCTION, value);
    }

    /**
     * Gets the attribute value for HmoAcceptanceFlag, using the alias name HmoAcceptanceFlag.
     * @return the value of HmoAcceptanceFlag
     */
    public String getHmoAcceptanceFlag() {
        return (String) getAttributeInternal(HMOACCEPTANCEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoAcceptanceFlag.
     * @param value value to set the HmoAcceptanceFlag
     */
    public void setHmoAcceptanceFlag(String value) {
        setAttributeInternal(HMOACCEPTANCEFLAG, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for EmpName_Trans, using the alias name EmpName_Trans.
     * @return the value of EmpName_Trans
     */
    public String getEmpName_Trans() {
        return (String) getAttributeInternal(EMPNAME_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpName_Trans.
     * @param value value to set the EmpName_Trans
     */
    public void setEmpName_Trans(String value) {
        setAttributeInternal(EMPNAME_TRANS, value);
    }

    /**
     * Gets the attribute value for EmpNumber_Trans, using the alias name EmpNumber_Trans.
     * @return the value of EmpNumber_Trans
     */
    public String getEmpNumber_Trans() {
        return (String) getAttributeInternal(EMPNUMBER_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmpNumber_Trans.
     * @param value value to set the EmpNumber_Trans
     */
    public void setEmpNumber_Trans(String value) {
        setAttributeInternal(EMPNUMBER_TRANS, value);
    }

    /**
     * Gets the attribute value for BusinessUnit_Trans, using the alias name BusinessUnit_Trans.
     * @return the value of BusinessUnit_Trans
     */
    public String getBusinessUnit_Trans() {
        return (String) getAttributeInternal(BUSINESSUNIT_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnit_Trans.
     * @param value value to set the BusinessUnit_Trans
     */
    public void setBusinessUnit_Trans(String value) {
        setAttributeInternal(BUSINESSUNIT_TRANS, value);
    }

    /**
     * Gets the attribute value for Email_Trans, using the alias name Email_Trans.
     * @return the value of Email_Trans
     */
    public String getEmail_Trans() {
        return (String) getAttributeInternal(EMAIL_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email_Trans.
     * @param value value to set the Email_Trans
     */
    public void setEmail_Trans(String value) {
        setAttributeInternal(EMAIL_TRANS, value);
    }

    /**
     * Gets the attribute value for DeptName_Trans, using the alias name DeptName_Trans.
     * @return the value of DeptName_Trans
     */
    public String getDeptName_Trans() {
        return (String) getAttributeInternal(DEPTNAME_TRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptName_Trans.
     * @param value value to set the DeptName_Trans
     */
    public void setDeptName_Trans(String value) {
        setAttributeInternal(DEPTNAME_TRANS, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for Hospital, using the alias name Hospital.
     * @return the value of Hospital
     */
    public String getHospital() {
        return (String) getAttributeInternal(HOSPITAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hospital.
     * @param value value to set the Hospital
     */
    public void setHospital(String value) {
        setAttributeInternal(HOSPITAL, value);
    }

    /**
     * Gets the attribute value for Photo, using the alias name Photo.
     * @return the value of Photo
     */
    public BlobDomain getPhoto() {
        return (BlobDomain) getAttributeInternal(PHOTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Photo.
     * @param value value to set the Photo
     */
    public void setPhoto(BlobDomain value) {
        setAttributeInternal(PHOTO, value);
    }

    /**
     * Gets the attribute value for StateOfResidence, using the alias name StateOfResidence.
     * @return the value of StateOfResidence
     */
    public String getStateOfResidence() {
        return (String) getAttributeInternal(STATEOFRESIDENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateOfResidence.
     * @param value value to set the StateOfResidence
     */
    public void setStateOfResidence(String value) {
        setAttributeInternal(STATEOFRESIDENCE, value);
    }

    /**
     * Gets the attribute value for AlternateEmail, using the alias name AlternateEmail.
     * @return the value of AlternateEmail
     */
    public String getAlternateEmail() {
        return (String) getAttributeInternal(ALTERNATEEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AlternateEmail.
     * @param value value to set the AlternateEmail
     */
    public void setAlternateEmail(String value) {
        setAttributeInternal(ALTERNATEEMAIL, value);
    }

    /**
     * Gets the attribute value for PhotoClob, using the alias name PhotoClob.
     * @return the value of PhotoClob
     */
    public ClobDomain getPhotoClob() {
        return (ClobDomain) getAttributeInternal(PHOTOCLOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhotoClob.
     * @param value value to set the PhotoClob
     */
    public void setPhotoClob(ClobDomain value) {
        setAttributeInternal(PHOTOCLOB, value);
    }

    /**
     * Gets the attribute value for HmoCopyDepFlag, using the alias name HmoCopyDepFlag.
     * @return the value of HmoCopyDepFlag
     */
    public String getHmoCopyDepFlag() {
        return (String) getAttributeInternal(HMOCOPYDEPFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoCopyDepFlag.
     * @param value value to set the HmoCopyDepFlag
     */
    public void setHmoCopyDepFlag(String value) {
        setAttributeInternal(HMOCOPYDEPFLAG, value);
    }

    /**
     * Gets the attribute value for AddiCategory, using the alias name AddiCategory.
     * @return the value of AddiCategory
     */
    public String getAddiCategory() {
        return (String) getAttributeInternal(ADDICATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddiCategory.
     * @param value value to set the AddiCategory
     */
    public void setAddiCategory(String value) {
        setAttributeInternal(ADDICATEGORY, value);
    }

    /**
     * Gets the attribute value for SoaFlowid, using the alias name SoaFlowid.
     * @return the value of SoaFlowid
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoaFlowid.
     * @param value value to set the SoaFlowid
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for PayrollBatchName, using the alias name PayrollBatchName.
     * @return the value of PayrollBatchName
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PayrollBatchName.
     * @param value value to set the PayrollBatchName
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for ErrorMsg, using the alias name ErrorMsg.
     * @return the value of ErrorMsg
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorMsg.
     * @param value value to set the ErrorMsg
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for ApproverComments, using the alias name ApproverComments.
     * @return the value of ApproverComments
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApproverComments.
     * @param value value to set the ApproverComments
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for ApprovalStatus, using the alias name ApprovalStatus.
     * @return the value of ApprovalStatus
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalStatus.
     * @param value value to set the ApprovalStatus
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for CopyDep, using the alias name CopyDep.
     * @return the value of CopyDep
     */
    public String getCopyDep() {
        return (String) getAttributeInternal(COPYDEP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CopyDep.
     * @param value value to set the CopyDep
     */
    public void setCopyDep(String value) {
        setAttributeInternal(COPYDEP, value);
    }

    /**
     * Gets the attribute value for HmoPlan, using the alias name HmoPlan.
     * @return the value of HmoPlan
     */
    public String getHmoPlan() {
        return (String) getAttributeInternal(HMOPLAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoPlan.
     * @param value value to set the HmoPlan
     */
    public void setHmoPlan(String value) {
        setAttributeInternal(HMOPLAN, value);
    }

    /**
     * Gets the attribute value for HmoEmpCost, using the alias name HmoEmpCost.
     * @return the value of HmoEmpCost
     */
    public BigDecimal getHmoEmpCost() {
        return (BigDecimal) getAttributeInternal(HMOEMPCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoEmpCost.
     * @param value value to set the HmoEmpCost
     */
    public void setHmoEmpCost(BigDecimal value) {
        setAttributeInternal(HMOEMPCOST, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxhrHmoTrxDtl_EO() {
        return (RowIterator) getAttributeInternal(XXHRHMOTRXDTL_EO);
    }


    /**
     * @param hmoTrxHdrId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number hmoTrxHdrId) {
        return new Key(new Object[] { hmoTrxHdrId });
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        System.out.println("Inside remove method....");
        RowIterator employees = getXxhrHmoTrxDtl_EO();
        while (employees.hasNext()) {
            //Delete all Employees
            employees.next().remove();
        }
        super.remove();
    }
}

