package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 27 23:49:15 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DutyAllowance_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ExtraDutyAllowanceId,
        ExtraDutyAllowanceNo,
        PersonId,
        BusinessUnitId,
        TransactionDate,
        AllowanceType,
        AllowanceRate,
        StartDate,
        EndDate,
        AllowanceDays,
        AllowanceAmount,
        Comments,
        ApprovalStatus,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int EXTRADUTYALLOWANCEID = AttributesEnum.ExtraDutyAllowanceId.index();
    public static final int EXTRADUTYALLOWANCENO = AttributesEnum.ExtraDutyAllowanceNo.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int ALLOWANCETYPE = AttributesEnum.AllowanceType.index();
    public static final int ALLOWANCERATE = AttributesEnum.AllowanceRate.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ALLOWANCEDAYS = AttributesEnum.AllowanceDays.index();
    public static final int ALLOWANCEAMOUNT = AttributesEnum.AllowanceAmount.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DutyAllowance_EOImpl() {
    }

    /**
     * Gets the attribute value for ExtraDutyAllowanceId, using the alias name ExtraDutyAllowanceId.
     * @return the value of ExtraDutyAllowanceId
     */
    public BigDecimal getExtraDutyAllowanceId() {
        return (BigDecimal) getAttributeInternal(EXTRADUTYALLOWANCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraDutyAllowanceId.
     * @param value value to set the ExtraDutyAllowanceId
     */
    public void setExtraDutyAllowanceId(BigDecimal value) {
        setAttributeInternal(EXTRADUTYALLOWANCEID, value);
    }

    /**
     * Gets the attribute value for ExtraDutyAllowanceNo, using the alias name ExtraDutyAllowanceNo.
     * @return the value of ExtraDutyAllowanceNo
     */
    public String getExtraDutyAllowanceNo() {
        return (String) getAttributeInternal(EXTRADUTYALLOWANCENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraDutyAllowanceNo.
     * @param value value to set the ExtraDutyAllowanceNo
     */
    public void setExtraDutyAllowanceNo(String value) {
        setAttributeInternal(EXTRADUTYALLOWANCENO, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for BusinessUnitId, using the alias name BusinessUnitId.
     * @return the value of BusinessUnitId
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnitId.
     * @param value value to set the BusinessUnitId
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for TransactionDate, using the alias name TransactionDate.
     * @return the value of TransactionDate
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionDate.
     * @param value value to set the TransactionDate
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for AllowanceType, using the alias name AllowanceType.
     * @return the value of AllowanceType
     */
    public String getAllowanceType() {
        return (String) getAttributeInternal(ALLOWANCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowanceType.
     * @param value value to set the AllowanceType
     */
    public void setAllowanceType(String value) {
        setAttributeInternal(ALLOWANCETYPE, value);
    }

    /**
     * Gets the attribute value for AllowanceRate, using the alias name AllowanceRate.
     * @return the value of AllowanceRate
     */
    public BigDecimal getAllowanceRate() {
        return (BigDecimal) getAttributeInternal(ALLOWANCERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowanceRate.
     * @param value value to set the AllowanceRate
     */
    public void setAllowanceRate(BigDecimal value) {
        setAttributeInternal(ALLOWANCERATE, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the value of EndDate
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for AllowanceDays, using the alias name AllowanceDays.
     * @return the value of AllowanceDays
     */
    public BigDecimal getAllowanceDays() {
        return (BigDecimal) getAttributeInternal(ALLOWANCEDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowanceDays.
     * @param value value to set the AllowanceDays
     */
    public void setAllowanceDays(BigDecimal value) {
        setAttributeInternal(ALLOWANCEDAYS, value);
    }

    /**
     * Gets the attribute value for AllowanceAmount, using the alias name AllowanceAmount.
     * @return the value of AllowanceAmount
     */
    public BigDecimal getAllowanceAmount() {
        return (BigDecimal) getAttributeInternal(ALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowanceAmount.
     * @param value value to set the AllowanceAmount
     */
    public void setAllowanceAmount(BigDecimal value) {
        setAttributeInternal(ALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ApprovalStatus, using the alias name ApprovalStatus.
     * @return the value of ApprovalStatus
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalStatus.
     * @param value value to set the ApprovalStatus
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * @param extraDutyAllowanceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal extraDutyAllowanceId) {
        return new Key(new Object[] { extraDutyAllowanceId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.DutyAllowance_EO");
    }
}

