package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 23 03:48:44 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhrHmoTrxDtl_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HmoTrxDtlId,
        HmoTrxHdrId,
        DependentType,
        DependentClass,
        DepDob,
        DepGender,
        DepTitle,
        DepAgeCategory,
        DepFirstName,
        DepLastName,
        ResiAddress,
        PersonId,
        MobileNo,
        MaritalStatus,
        ResidentialAddress,
        StateOfResidence,
        Hospital,
        DependentCost,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        DepPhoto,
        Code_Trans,
        DepPhotoClob,
        XxhrHmoTrxHdr_EO,
        XxfndAttachment_EO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HMOTRXDTLID = AttributesEnum.HmoTrxDtlId.index();
    public static final int HMOTRXHDRID = AttributesEnum.HmoTrxHdrId.index();
    public static final int DEPENDENTTYPE = AttributesEnum.DependentType.index();
    public static final int DEPENDENTCLASS = AttributesEnum.DependentClass.index();
    public static final int DEPDOB = AttributesEnum.DepDob.index();
    public static final int DEPGENDER = AttributesEnum.DepGender.index();
    public static final int DEPTITLE = AttributesEnum.DepTitle.index();
    public static final int DEPAGECATEGORY = AttributesEnum.DepAgeCategory.index();
    public static final int DEPFIRSTNAME = AttributesEnum.DepFirstName.index();
    public static final int DEPLASTNAME = AttributesEnum.DepLastName.index();
    public static final int RESIADDRESS = AttributesEnum.ResiAddress.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int MARITALSTATUS = AttributesEnum.MaritalStatus.index();
    public static final int RESIDENTIALADDRESS = AttributesEnum.ResidentialAddress.index();
    public static final int STATEOFRESIDENCE = AttributesEnum.StateOfResidence.index();
    public static final int HOSPITAL = AttributesEnum.Hospital.index();
    public static final int DEPENDENTCOST = AttributesEnum.DependentCost.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int DEPPHOTO = AttributesEnum.DepPhoto.index();
    public static final int CODE_TRANS = AttributesEnum.Code_Trans.index();
    public static final int DEPPHOTOCLOB = AttributesEnum.DepPhotoClob.index();
    public static final int XXHRHMOTRXHDR_EO = AttributesEnum.XxhrHmoTrxHdr_EO.index();
    public static final int XXFNDATTACHMENT_EO = AttributesEnum.XxfndAttachment_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhrHmoTrxDtl_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.XxhrHmoTrxDtl_EO");
    }


    /**
     * Gets the attribute value for HmoTrxDtlId, using the alias name HmoTrxDtlId.
     * @return the value of HmoTrxDtlId
     */
    public DBSequence getHmoTrxDtlId() {
        return (DBSequence) getAttributeInternal(HMOTRXDTLID);
    }

    /**
     * Gets the attribute value for HmoTrxHdrId, using the alias name HmoTrxHdrId.
     * @return the value of HmoTrxHdrId
     */
    public Number getHmoTrxHdrId() {
        return (Number) getAttributeInternal(HMOTRXHDRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HmoTrxHdrId.
     * @param value value to set the HmoTrxHdrId
     */
    public void setHmoTrxHdrId(Number value) {
        setAttributeInternal(HMOTRXHDRID, value);
    }

    /**
     * Gets the attribute value for DependentType, using the alias name DependentType.
     * @return the value of DependentType
     */
    public String getDependentType() {
        return (String) getAttributeInternal(DEPENDENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DependentType.
     * @param value value to set the DependentType
     */
    public void setDependentType(String value) {
        setAttributeInternal(DEPENDENTTYPE, value);
    }

    /**
     * Gets the attribute value for DependentClass, using the alias name DependentClass.
     * @return the value of DependentClass
     */
    public String getDependentClass() {
        return (String) getAttributeInternal(DEPENDENTCLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DependentClass.
     * @param value value to set the DependentClass
     */
    public void setDependentClass(String value) {
        setAttributeInternal(DEPENDENTCLASS, value);
    }

    /**
     * Gets the attribute value for DepDob, using the alias name DepDob.
     * @return the value of DepDob
     */
    public Timestamp getDepDob() {
        return (Timestamp) getAttributeInternal(DEPDOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepDob.
     * @param value value to set the DepDob
     */
    public void setDepDob(Timestamp value) {
        setAttributeInternal(DEPDOB, value);
    }

    /**
     * Gets the attribute value for DepGender, using the alias name DepGender.
     * @return the value of DepGender
     */
    public String getDepGender() {
        return (String) getAttributeInternal(DEPGENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepGender.
     * @param value value to set the DepGender
     */
    public void setDepGender(String value) {
        setAttributeInternal(DEPGENDER, value);
    }

    /**
     * Gets the attribute value for DepTitle, using the alias name DepTitle.
     * @return the value of DepTitle
     */
    public String getDepTitle() {
        return (String) getAttributeInternal(DEPTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepTitle.
     * @param value value to set the DepTitle
     */
    public void setDepTitle(String value) {
        setAttributeInternal(DEPTITLE, value);
    }

    /**
     * Gets the attribute value for DepAgeCategory, using the alias name DepAgeCategory.
     * @return the value of DepAgeCategory
     */
    public String getDepAgeCategory() {
        return (String) getAttributeInternal(DEPAGECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepAgeCategory.
     * @param value value to set the DepAgeCategory
     */
    public void setDepAgeCategory(String value) {
        setAttributeInternal(DEPAGECATEGORY, value);
    }

    /**
     * Gets the attribute value for DepFirstName, using the alias name DepFirstName.
     * @return the value of DepFirstName
     */
    public String getDepFirstName() {
        return (String) getAttributeInternal(DEPFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepFirstName.
     * @param value value to set the DepFirstName
     */
    public void setDepFirstName(String value) {
        setAttributeInternal(DEPFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for DepLastName, using the alias name DepLastName.
     * @return the value of DepLastName
     */
    public String getDepLastName() {
        return (String) getAttributeInternal(DEPLASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepLastName.
     * @param value value to set the DepLastName
     */
    public void setDepLastName(String value) {
        setAttributeInternal(DEPLASTNAME, value);
    }

    /**
     * Gets the attribute value for ResiAddress, using the alias name ResiAddress.
     * @return the value of ResiAddress
     */
    public String getResiAddress() {
        return (String) getAttributeInternal(RESIADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResiAddress.
     * @param value value to set the ResiAddress
     */
    public void setResiAddress(String value) {
        setAttributeInternal(RESIADDRESS, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the value of MobileNo
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for MaritalStatus, using the alias name MaritalStatus.
     * @return the value of MaritalStatus
     */
    public String getMaritalStatus() {
        return (String) getAttributeInternal(MARITALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaritalStatus.
     * @param value value to set the MaritalStatus
     */
    public void setMaritalStatus(String value) {
        setAttributeInternal(MARITALSTATUS, value);
    }

    /**
     * Gets the attribute value for ResidentialAddress, using the alias name ResidentialAddress.
     * @return the value of ResidentialAddress
     */
    public String getResidentialAddress() {
        return (String) getAttributeInternal(RESIDENTIALADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResidentialAddress.
     * @param value value to set the ResidentialAddress
     */
    public void setResidentialAddress(String value) {
        setAttributeInternal(RESIDENTIALADDRESS, value);
    }

    /**
     * Gets the attribute value for StateOfResidence, using the alias name StateOfResidence.
     * @return the value of StateOfResidence
     */
    public String getStateOfResidence() {
        return (String) getAttributeInternal(STATEOFRESIDENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateOfResidence.
     * @param value value to set the StateOfResidence
     */
    public void setStateOfResidence(String value) {
        setAttributeInternal(STATEOFRESIDENCE, value);
    }

    /**
     * Gets the attribute value for Hospital, using the alias name Hospital.
     * @return the value of Hospital
     */
    public String getHospital() {
        return (String) getAttributeInternal(HOSPITAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hospital.
     * @param value value to set the Hospital
     */
    public void setHospital(String value) {
        setAttributeInternal(HOSPITAL, value);
    }

    /**
     * Gets the attribute value for DependentCost, using the alias name DependentCost.
     * @return the value of DependentCost
     */
    public BigDecimal getDependentCost() {
        return (BigDecimal) getAttributeInternal(DEPENDENTCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for DependentCost.
     * @param value value to set the DependentCost
     */
    public void setDependentCost(BigDecimal value) {
        setAttributeInternal(DEPENDENTCOST, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }


    /**
     * Gets the attribute value for DepPhoto, using the alias name DepPhoto.
     * @return the value of DepPhoto
     */
    public BlobDomain getDepPhoto() {
        return (BlobDomain) getAttributeInternal(DEPPHOTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepPhoto.
     * @param value value to set the DepPhoto
     */
    public void setDepPhoto(BlobDomain value) {
        setAttributeInternal(DEPPHOTO, value);
    }


    /**
     * Gets the attribute value for Code_Trans, using the alias name Code_Trans.
     * @return the value of Code_Trans
     */
    public String getCode_Trans() {
        return (String) getAttributeInternal(CODE_TRANS);
    }


    /**
     * Gets the attribute value for DepPhotoClob, using the alias name DepPhotoClob.
     * @return the value of DepPhotoClob
     */
    public ClobDomain getDepPhotoClob() {
        return (ClobDomain) getAttributeInternal(DEPPHOTOCLOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepPhotoClob.
     * @param value value to set the DepPhotoClob
     */
    public void setDepPhotoClob(ClobDomain value) {
        setAttributeInternal(DEPPHOTOCLOB, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getXxhrHmoTrxHdr_EO() {
        return (EntityImpl) getAttributeInternal(XXHRHMOTRXHDR_EO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setXxhrHmoTrxHdr_EO(EntityImpl value) {
        setAttributeInternal(XXHRHMOTRXHDR_EO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxfndAttachment_EO() {
        return (RowIterator) getAttributeInternal(XXFNDATTACHMENT_EO);
    }

    /**
     * @param hmoTrxDtlId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence hmoTrxDtlId) {
        return new Key(new Object[] { hmoTrxDtlId });
    }


}

