package model.am.common;

import java.util.ArrayList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 16 13:11:55 IST 2020
// ---------------------------------------------------------------------
public interface Oando_AM extends ApplicationModule {
    void createNewHMO();

    ArrayList getHMOCost(double p_hmo_trx_hdr_id, String p_hmo_request_date, double p_hmo_master_hdr_id,
                         String p_hmo_type, long p_person_id, String p_hmo_category, String p_hmo_option,
                         double p_hmo_plan_total, String p_dependent_type, String p_dep_dob, String p_addi_category);

    ArrayList getAgeCategory(double p_hmo_trx_hdr_id, String p_hmo_request_date, double p_hmo_master_hdr_id,
                             String p_hmo_type, long p_person_id, String p_hmo_category, String p_hmo_option,
                             double p_hmo_plan_total, String p_dependent_type, String p_dep_dob);

    ArrayList getEmpHmoCost(double p_hmo_master_hdr_id, String p_hmo_type, long p_person_id, String p_hmo_category,
                            String p_hmo_option, String p_emp_dob, String p_addi_category);

    ArrayList getEmpAgeCategory(double p_hmo_master_hdr_id, String p_hmo_type, String p_emp_dob);

    ArrayList createNewDependentRequest(String hmo_ref_no);

    String updateDeleteFlag(String hmo_ref_no, String req_type);

    ArrayList copyDepDetails(String hmo_ref_no);
}

