package model.ro;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 28 10:31:30 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxhrHmoMasterHdr_ROVORowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HmoMasterHdrId,
        BusinessUnitId,
        HmoPlanName,
        HmoPlanYear,
        BupaEligibleCost,
        BupaCurrencyCode,
        Active,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        AxaLbCurrencyCode,
        AxaLbEligibleCost;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HMOMASTERHDRID = AttributesEnum.HmoMasterHdrId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int HMOPLANNAME = AttributesEnum.HmoPlanName.index();
    public static final int HMOPLANYEAR = AttributesEnum.HmoPlanYear.index();
    public static final int BUPAELIGIBLECOST = AttributesEnum.BupaEligibleCost.index();
    public static final int BUPACURRENCYCODE = AttributesEnum.BupaCurrencyCode.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int AXALBCURRENCYCODE = AttributesEnum.AxaLbCurrencyCode.index();
    public static final int AXALBELIGIBLECOST = AttributesEnum.AxaLbEligibleCost.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxhrHmoMasterHdr_ROVORowImpl() {
    }
}

