package model.svo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 23 12:33:27 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DependentClass_SVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DependentClass_SVOImpl() {
    }
}

