package model.svo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 22 16:58:41 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupValue_SVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LookupValue_SVOImpl() {
    }
}

