package model.vo;

import java.sql.Timestamp;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 28 02:37:22 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxfndAttachment_EOViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_XXFNDATTACHMENT_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AttachmentId,
        AttachmentName,
        SourceDocument,
        SourceDocumentId,
        AttachmentType,
        Attachment,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        XxhrHmoTrxDtl_EOView,
        XxhrHmoCard_VO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTACHMENTID = AttributesEnum.AttachmentId.index();
    public static final int ATTACHMENTNAME = AttributesEnum.AttachmentName.index();
    public static final int SOURCEDOCUMENT = AttributesEnum.SourceDocument.index();
    public static final int SOURCEDOCUMENTID = AttributesEnum.SourceDocumentId.index();
    public static final int ATTACHMENTTYPE = AttributesEnum.AttachmentType.index();
    public static final int ATTACHMENT = AttributesEnum.Attachment.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int XXHRHMOTRXDTL_EOVIEW = AttributesEnum.XxhrHmoTrxDtl_EOView.index();
    public static final int XXHRHMOCARD_VO = AttributesEnum.XxhrHmoCard_VO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxfndAttachment_EOViewRowImpl() {
    }

    /**
     * Gets XxfndAttachment_EO entity object.
     * @return the XxfndAttachment_EO
     */
    public EntityImpl getXxfndAttachment_EO() {
        return (EntityImpl) getEntity(ENTITY_XXFNDATTACHMENT_EO);
    }

    /**
     * Gets the attribute value for ATTACHMENT_ID using the alias name AttachmentId.
     * @return the ATTACHMENT_ID
     */
    public DBSequence getAttachmentId() {
        return (DBSequence) getAttributeInternal(ATTACHMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT_ID using the alias name AttachmentId.
     * @param value value to set the ATTACHMENT_ID
     */
    public void setAttachmentId(DBSequence value) {
        setAttributeInternal(ATTACHMENTID, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT_NAME using the alias name AttachmentName.
     * @return the ATTACHMENT_NAME
     */
    public String getAttachmentName() {
        return (String) getAttributeInternal(ATTACHMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT_NAME using the alias name AttachmentName.
     * @param value value to set the ATTACHMENT_NAME
     */
    public void setAttachmentName(String value) {
        setAttributeInternal(ATTACHMENTNAME, value);
    }

    /**
     * Gets the attribute value for SOURCE_DOCUMENT using the alias name SourceDocument.
     * @return the SOURCE_DOCUMENT
     */
    public String getSourceDocument() {
        return (String) getAttributeInternal(SOURCEDOCUMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_DOCUMENT using the alias name SourceDocument.
     * @param value value to set the SOURCE_DOCUMENT
     */
    public void setSourceDocument(String value) {
        setAttributeInternal(SOURCEDOCUMENT, value);
    }

    /**
     * Gets the attribute value for SOURCE_DOCUMENT_ID using the alias name SourceDocumentId.
     * @return the SOURCE_DOCUMENT_ID
     */
    public Number getSourceDocumentId() {
        return (Number) getAttributeInternal(SOURCEDOCUMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_DOCUMENT_ID using the alias name SourceDocumentId.
     * @param value value to set the SOURCE_DOCUMENT_ID
     */
    public void setSourceDocumentId(Number value) {
        setAttributeInternal(SOURCEDOCUMENTID, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT_TYPE using the alias name AttachmentType.
     * @return the ATTACHMENT_TYPE
     */
    public String getAttachmentType() {
        return (String) getAttributeInternal(ATTACHMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT_TYPE using the alias name AttachmentType.
     * @param value value to set the ATTACHMENT_TYPE
     */
    public void setAttachmentType(String value) {
        setAttributeInternal(ATTACHMENTTYPE, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT using the alias name Attachment.
     * @return the ATTACHMENT
     */
    public BlobDomain getAttachment() {
        return (BlobDomain) getAttributeInternal(ATTACHMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT using the alias name Attachment.
     * @param value value to set the ATTACHMENT
     */
    public void setAttachment(BlobDomain value) {
        setAttributeInternal(ATTACHMENT, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the associated <code>XxhrHmoTrxDtl_EOViewRowImpl</code> using master-detail link XxhrHmoTrxDtl_EOView.
     */
    public XxhrHmoTrxDtl_EOViewRowImpl getXxhrHmoTrxDtl_EOView() {
        return (XxhrHmoTrxDtl_EOViewRowImpl) getAttributeInternal(XXHRHMOTRXDTL_EOVIEW);
    }

    /**
     * Sets the master-detail link XxhrHmoTrxDtl_EOView between this object and <code>value</code>.
     */
    public void setXxhrHmoTrxDtl_EOView(XxhrHmoTrxDtl_EOViewRowImpl value) {
        setAttributeInternal(XXHRHMOTRXDTL_EOVIEW, value);
    }

    /**
     * Gets the associated <code>ViewRowImpl</code> using master-detail link XxhrHmoCard_VO.
     */
    public ViewRowImpl getXxhrHmoCard_VO() {
        return (ViewRowImpl) getAttributeInternal(XXHRHMOCARD_VO);
    }

    /**
     * Sets the master-detail link XxhrHmoCard_VO between this object and <code>value</code>.
     */
    public void setXxhrHmoCard_VO(ViewRowImpl value) {
        setAttributeInternal(XXHRHMOCARD_VO, value);
    }
}

