package model.am;


import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;

import model.am.common.Oando_AM;

import model.ro.MaximumEligibleCost_ROVOImpl;
import model.ro.XxhrHmoMasterHdr_ROVOImpl;

import model.svo.DependentClass_SVOImpl;
import model.svo.LookupType_SVOImpl;
import model.svo.LookupValue_SVOImpl;

import model.vo.DutyAllowance_VOImpl;
import model.vo.XxfndAttachment_EOViewImpl;
import model.vo.XxhrHmoTrxDtl_EOViewImpl;
import model.vo.XxhrHmoTrxDtl_EOViewRowImpl;
import model.vo.XxhrHmoTrxHdr_EOViewImpl;
import model.vo.XxhrHmoTrxHdr_EOViewRowImpl;

import oracle.adf.share.ADFContext;

import oracle.jbo.ApplicationModule;
import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 22 17:52:17 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

public class Oando_AMImpl extends ApplicationModuleImpl implements ApplicationModule, Oando_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Oando_AMImpl() {
    }

    public BigDecimal getPersonId(String userName) {
        System.out.println("UserName::::: " + userName);
        BigDecimal personId = new BigDecimal(0);
        ViewObjectImpl vo = this.getUsers_ROVO();
        ViewCriteria vc = vo.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
        vcRow.setAttribute("Username", userName);
        vc.addRow(vcRow);
        vo.applyViewCriteria(vc);
        vo.executeQuery();
        if (vo.getEstimatedRowCount() > 0) {
            personId = (BigDecimal) vo.first().getAttribute("PersonId");
            System.out.println("PersonId:: " + personId);
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("personId", personId);
        }

        return personId;
    }
 
    public void createNewHMO() {
        String empName = null;
        String empNumber = null;
        String businessUnit = null;
        Number businessUnitId = new Number(0);
        String email = null;
        String deptName = null;
        String title =null;
        String firstName=null;
        String lastName=null; 
        String userName = ADFContext.getCurrent().getSessionScope().get("userName").toString(); 
        try {
            Number personId = new Number(getPersonId(userName)); 
            ViewObjectImpl vo = this.getXxperEmployee_V_ROVO1();
            ViewCriteria vc = vo.createViewCriteria();
            ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
            vcRow.setAttribute("PersonId", personId);
            vc.addRow(vcRow);
            vo.applyViewCriteria(vc);
            vo.executeQuery();
            if (vo.getEstimatedRowCount() > 0) {
                Row r = vo.first();
                businessUnitId = new Number(vo.first().getAttribute("BusinessUnitId"));
                empName = r.getAttribute("DisplayName")!=null?r.getAttribute("DisplayName").toString():"";
                empNumber = r.getAttribute("PersonNumber")!=null?r.getAttribute("PersonNumber").toString():"";
                businessUnit = r.getAttribute("BusinessUnitName")!=null?r.getAttribute("BusinessUnitName").toString():"";
                deptName = r.getAttribute("DepartmentName")!=null?r.getAttribute("DepartmentName").toString():"";
                title = r.getAttribute("Title")!=null?r.getAttribute("Title").toString():"";
                firstName = r.getAttribute("FirstName")!=null?r.getAttribute("FirstName").toString():"";
                lastName = r.getAttribute("LastName")!=null?r.getAttribute("LastName").toString():"";
            }
            
            ViewObject hdrVo = this.getXxhrHmoTrxHdr_EOView();
            XxhrHmoTrxHdr_EOViewRowImpl newRow = (XxhrHmoTrxHdr_EOViewRowImpl) hdrVo.createRow();
            newRow.setPersonId(personId);
//            newRow.setHmoRequestNo(" ");
            newRow.setBusinessUnitId(businessUnitId);
            newRow.setEmpName_Trans(empName);
            newRow.setEmpNumber_Trans(empNumber);
            newRow.setBusinessUnit_Trans(businessUnit);
            newRow.setEmail_Trans(email);
            newRow.setDeptName_Trans(deptName);
            newRow.setHmoAcceptanceFlag("N");
            newRow.setHmoCopyDepFlag("N");
            newRow.setCreatedBy(empName);
            newRow.setTrans_Title(title);
            newRow.setTrans_FirstName(firstName);
            newRow.setTrans_LastName(lastName);
            hdrVo.insertRow(newRow);
        } catch (SQLException e) {
        }
    }

    public void editHmoRequest(Number hmoHdrId) {
        String empName = null;
        String empNumber = null;
        String businessUnit = null;
        Number businessUnitId = new Number(0);
        String email = null;
        String deptName = null;
        String title =null;
        String firstName=null;
        String lastName=null;
        String gender=null;
        String empDob=null;

        System.out.println("HeaderID inside edit mode method:::: " + hmoHdrId);
        ViewObject vo = this.getXxhrHmoTrxHdr_EOView();
        ViewCriteria vc = vo.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
        vcRow.setAttribute("HmoTrxHdrId", hmoHdrId);
        vc.addRow(vcRow);
        vo.applyViewCriteria(vc);
        vo.executeQuery();
        System.out.println("Get Query in edit mode ---- " + vo.getQuery());
        /**
         * Fetch required details from employee table
         */
        String userName = ADFContext.getCurrent()
                                    .getSessionScope()
                                    .get("userName")
                                    .toString();
        Number personId;
        try {
            personId = new Number(getPersonId(userName));
            ViewObjectImpl vo1 = this.getXxperEmployee_V_ROVO1();
            ViewCriteria vc1 = vo1.createViewCriteria();
            ViewCriteriaRow vcRow1 = vc1.createViewCriteriaRow();
            vcRow1.setAttribute("PersonId", personId);
            vc1.addRow(vcRow1);
            vo1.applyViewCriteria(vc1);
            vo1.executeQuery();
            if (vo1.getEstimatedRowCount() > 0) {
                businessUnitId = new Number(vo1.first().getAttribute("BusinessUnitId"));
                empName = (String) vo1.first().getAttribute("DisplayName");
                empNumber = (String) vo1.first().getAttribute("PersonNumber");
                businessUnit = (String) vo1.first().getAttribute("BusinessUnitName");
                email = (String) vo1.first().getAttribute("EmailAddress");
                deptName = (String) vo1.first().getAttribute("DepartmentName");
                title = (String) vo1.first().getAttribute("Title");
                firstName = (String) vo1.first().getAttribute("FirstName");
                lastName = (String) vo1.first().getAttribute("LastName");
                gender = (String) vo1.first().getAttribute("SexDesc");
               // empDob = (String) vo1.first().getAttribute("DateOfBirth");
               // empDate = (String) vo1.first().getAttribute("SexDesc");
                
                ViewObject hdrVo = this.getXxhrHmoTrxHdr_EOView();
                Row newRow = hdrVo.first();
              //  System.out.println("Header Id in edit mode ----- " + newRow.getAttribute("HmoTrxHdrId"));
                newRow.setAttribute("PersonId", personId);
                newRow.setAttribute("BusinessUnitId", businessUnitId);
                newRow.setAttribute("EmpName_Trans", empName);
                newRow.setAttribute("EmpNumber_Trans", empNumber);
                newRow.setAttribute("Email_Trans", email);
                newRow.setAttribute("DeptName_Trans", deptName);
                newRow.setAttribute("HmoAcceptanceFlag", newRow.getAttribute("HmoAcceptanceFlag"));
                newRow.setAttribute("HmoCopyDepFlag", newRow.getAttribute("HmoCopyDepFlag"));
                newRow.setAttribute("Trans_Title", title);
                newRow.setAttribute("Trans_FirstName", firstName);
                newRow.setAttribute("Trans_LastName", lastName);
                newRow.setAttribute("Gender", gender);
               // newRow.setAttribute("Trans_DateofBirth", empDob);              
                //newRow.setAttribute("Gender", empDate);
            }
        } catch (SQLException e) {
        }

    }

    public void createHMODetailRow(String classType) {
        System.out.println("Classs:::: " + classType);
        String userName = ADFContext.getCurrent()
                                    .getSessionScope()
                                    .get("userName")
                                    .toString();
        //   String create = ADFContext.getCurrent()
        //                                    .getPageFlowScope()
        //                                    .get("toBeCreated")
        //                                    .toString();


        try {
            Number personId = new Number(getPersonId(userName));
            /**
         * Create row in Detail table, setting above values in its respective fields
         */
            //    if("true".equalsIgnoreCase(create)){
            if ("SELF".equalsIgnoreCase(classType)) {
                System.out.println("Firstssss");
                ViewObject dtlVo = this.getXxhrHmoTrxDtl_EOView();
                XxhrHmoTrxDtl_EOViewRowImpl newRow = (XxhrHmoTrxDtl_EOViewRowImpl) dtlVo.createRow();
                newRow.setDependentClass(classType);
                newRow.setPersonId(personId);
                newRow.setCreatedBy(userName);
              //  newRow.setCreationDate(new java.sql.Timestamp(System.currentTimeMillis()));
                dtlVo.insertRow(newRow);
                ADFContext.getCurrent()
                          .getPageFlowScope()
                          .put("toBeCreated", "false");
            } else {
                System.out.println("SEcccccc");
                ViewObject dtlVo = this.getXxhrHmoTrxDtl_Others_EOView();
                XxhrHmoTrxDtl_EOViewRowImpl newRow = (XxhrHmoTrxDtl_EOViewRowImpl) dtlVo.createRow();
                newRow.setDependentClass(classType);
                newRow.setPersonId(personId);
                newRow.setCreatedBy(userName);
             //   newRow.setCreationDate(new java.sql.Timestamp(System.currentTimeMillis()));
                dtlVo.insertRow(newRow);
                ADFContext.getCurrent()
                          .getPageFlowScope()
                          .put("toBeCreated", "false");
            }
            //  }
        } catch (SQLException e) {
        }
    }

    public ArrayList getAgeCategory(double p_hmo_trx_hdr_id, String p_hmo_request_date, double p_hmo_master_hdr_id,
                                 String p_hmo_type, long p_person_id, String p_hmo_category, String p_hmo_option,
                                 double p_hmo_plan_total, String p_dependent_type,
                                 String p_dep_dob) {
        ArrayList list = new ArrayList();
        CallableStatement st = null;
        try {
            DateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            java.util.Date reqday = inputFormat.parse(p_hmo_request_date);
            java.sql.Date reqDate = new java.sql.Date(reqday.getTime());
            java.util.Date depday = inputFormat.parse(p_dep_dob);
            java.sql.Date depDate = new java.sql.Date(depday.getTime());
            st =
                this.getDBTransaction()
                .createCallableStatement("BEGIN ? :=  xxhr_hmo_pkg.age_category(?,?,?,?,?,?,?,?,?,?);END;", 0);

            st.registerOutParameter(1, Types.VARCHAR);
            st.setDouble(2, p_hmo_trx_hdr_id);
            st.setDate(3, reqDate);
            st.setDouble(4, p_hmo_master_hdr_id);
            st.setString(5, p_hmo_type);
            st.setLong(6, p_person_id);
            st.setString(7, p_hmo_category);
            st.setString(8, p_hmo_option);
            st.setDouble(9, p_hmo_plan_total);
            st.setString(10, p_dependent_type);
            st.setDate(11, depDate);
            st.executeUpdate();
            list.add(st.getString(1));
        } catch (SQLException e) {
            throw new JboException(e.getMessage());

        } catch (ParseException e) {
        } finally {
            if (st != null) {
                try {
                    st.close();
                } catch (SQLException e) {
                }
            }
        }

        return list;
    }


    /**Method to set file path and name
     * @param name
     * @param path
     */
    public void setFileData(String name, String sourceCode, String contTyp, String type) {
        System.out.println("Entered ...");
        if ("SELF".equalsIgnoreCase(type)) {
            System.out.println("IF STmt");
            ViewObject fileVo = this.getSelfAttachment_EOView();
            Row newRow = fileVo.createRow();
            newRow.setAttribute("AttachmentName", name);
            newRow.setAttribute("SourceDocument", type);
            newRow.setAttribute("AttachmentType", contTyp);
            fileVo.insertRow(newRow);
            System.out.println("Created Successfully");
        } else {
            System.out.println("Else Stmt....");
            ViewObject fileVo = this.getOthersAttachment_EOView();
            Row newRow = fileVo.createRow();
            newRow.setAttribute("AttachmentName", name);
            newRow.setAttribute("SourceDocument", type);
            newRow.setAttribute("AttachmentType", contTyp);
            fileVo.insertRow(newRow);
            System.out.println("Creeg ......");
        }
    }

    /**Method to check for duplicate files
     * @param fileNm
     * @return
     */
    public String checkDuplicateFile_Self(String fileNm) {
        ViewObject fileVo = this.getSelfAttachment_EOView();
        Row duplFile[] = fileVo.getFilteredRows("AttachmentName", fileNm);
        if (duplFile.length > 0) {
            return "N";
        } else {
            return "Y";
        }
    }

    /**Method to check for duplicate dependent type
     * @param fileNm
     * @return
     */
    public String checkDuplicateDept_Self(Number personId) {
        ViewObject deptVo = this.getXxhrHmoTrxDtl_EOView();
        Row duplType[] = deptVo.getFilteredRows("PersonId", personId);
        System.out.println("PersonIDD:: " + personId + "Length::: " + duplType.length);
        if (duplType.length > 1) {
            XxhrHmoTrxDtl_EOViewRowImpl row = (XxhrHmoTrxDtl_EOViewRowImpl) deptVo.getCurrentRow();
            row.getSelfDependent_ROVO().executeQuery();
            return "N";
        } else {
            return "Y";
        }
    }

    /**
     * gets the current existing database connection
     * @return Connection-Object
     */
    public Connection getCurrentConnection() {
        Statement st = null;
        try {
            st = getDBTransaction().createStatement(0);
            return st.getConnection();
        } catch (Exception s) {
            s.printStackTrace();
            return null;
        } finally {
            if (st != null)
                try {
                    st.close();
                } catch (Exception s2) {
                }
        }
    }

    /**Method to check for duplicate files
     * @param fileNm
     * @return
     */
    public String checkDuplicateFile_Others(String fileNm) {
        ViewObject fileVo = this.getOthersAttachment_EOView();
        Row duplFile[] = fileVo.getFilteredRows("AttachmentName", fileNm);
        if (duplFile.length > 0) {
            return "N";
        } else {
            return "Y";
        }
    }

    /**
     * Container's getter for Users_ROVO1.
     * @return Users_ROVO1
     */
    public ViewObjectImpl getUsers_ROVO() {
        return (ViewObjectImpl) findViewObject("Users_ROVO");
    }

    /**
     * Container's getter for Employee_View_ROVO1.
     * @return Employee_View_ROVO1
     */
    public ViewObjectImpl getEmployee_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Employee_View_ROVO");
    }


    /**
     * Container's getter for XxhrHmoTrxHdr_ROVO1.
     * @return XxhrHmoTrxHdr_ROVO1
     */
    public ViewObjectImpl getXxhrHmoTrxHdr_ROVO1() {
        return (ViewObjectImpl) findViewObject("XxhrHmoTrxHdr_ROVO1");
    }


    /**
     * Container's getter for LookupValue_SVO1.
     * @return LookupValue_SVO1
     */
    public LookupValue_SVOImpl getLookupValue_SVO1() {
        return (LookupValue_SVOImpl) findViewObject("LookupValue_SVO1");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO1.
     * @return XxfndLookupValues_V_ROVO1
     */
    public ViewObjectImpl getBUPA_Option_LOV() {
        return (ViewObjectImpl) findViewObject("BUPA_Option_LOV");
    }

    /**
     * Container's getter for XxperEmployee_V_ROVO1.
     * @return XxperEmployee_V_ROVO1
     */
    public ViewObjectImpl getXxperEmployee_V_ROVO1() {
        return (ViewObjectImpl) findViewObject("XxperEmployee_V_ROVO1");
    }

    /**
     * Container's getter for XxperEmpDependent_V_ROVO1.
     * @return XxperEmpDependent_V_ROVO1
     */
    public ViewObjectImpl getSelfDependent_ROVO() {
        return (ViewObjectImpl) findViewObject("SelfDependent_ROVO");
    }

    /**
     * Container's getter for DutyAllowance_VO1.
     * @return DutyAllowance_VO1
     */
    public DutyAllowance_VOImpl getDutyAllowance_VO() {
        return (DutyAllowance_VOImpl) findViewObject("DutyAllowance_VO");
    }

    /**
     * Container's getter for DutyAllow_ROVO1.
     * @return DutyAllow_ROVO1
     */
    public ViewObjectImpl getDutyAllow_ROVO1() {
        return (ViewObjectImpl) findViewObject("DutyAllow_ROVO1");
    }

    /**
     * Container's getter for ExtraDutyAllowanceROVO1.
     * @return ExtraDutyAllowanceROVO1
     */
    public ViewObjectImpl getExtraDutyAllowanceROVO1() {
        return (ViewObjectImpl) findViewObject("ExtraDutyAllowanceROVO1");
    }

    /**
     * Container's getter for XxhrHmoTrxHdr_EOView2.
     * @return XxhrHmoTrxHdr_EOView2
     */
    public XxhrHmoTrxHdr_EOViewImpl getXxhrHmoTrxHdr_EOView() {
        return (XxhrHmoTrxHdr_EOViewImpl) findViewObject("XxhrHmoTrxHdr_EOView");
    }

    /**
     * Container's getter for XxhrHmoTrxDtl_EOView2.
     * @return XxhrHmoTrxDtl_EOView2
     */
    public XxhrHmoTrxDtl_EOViewImpl getXxhrHmoTrxDtl_EOView() {
        return (XxhrHmoTrxDtl_EOViewImpl) findViewObject("XxhrHmoTrxDtl_EOView");
    }

    /**
     * Container's getter for XxhrHmoHdr_Dtl_VL.
     * @return XxhrHmoHdr_Dtl_VL
     */
    public ViewLinkImpl getXxhrHmoHdr_Dtl_VL() {
        return (ViewLinkImpl) findViewLink("XxhrHmoHdr_Dtl_VL");
    }

    /**
     * Container's getter for LookupType_SVO1.
     * @return LookupType_SVO1
     */
    public LookupType_SVOImpl getLookupType_SVO1() {
        return (LookupType_SVOImpl) findViewObject("LookupType_SVO1");
    }

    /**
     * Container's getter for DependentClass_SVO1.
     * @return DependentClass_SVO1
     */
    public DependentClass_SVOImpl getDependentClass_SVO1() {
        return (DependentClass_SVOImpl) findViewObject("DependentClass_SVO1");
    }

    /**
     * Container's getter for XxhrHmoTrxDtl_EOView1.
     * @return XxhrHmoTrxDtl_EOView1
     */
    public XxhrHmoTrxDtl_EOViewImpl getXxhrHmoTrxDtl_Others_EOView() {
        return (XxhrHmoTrxDtl_EOViewImpl) findViewObject("XxhrHmoTrxDtl_Others_EOView");
    }

    /**
     * Container's getter for XxhrHmoHdr_Dtl_VL1.
     * @return XxhrHmoHdr_Dtl_VL1
     */
    public ViewLinkImpl getXxhrHmoHdr_Dtl_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrHmoHdr_Dtl_VL1");
    }


    /**
     * Container's getter for XxfndLookupValues_V_ROVO2.
     * @return XxfndLookupValues_V_ROVO2
     */
    public ViewObjectImpl getBUPA_Cat_LOV() {
        return (ViewObjectImpl) findViewObject("BUPA_Cat_LOV");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO3.
     * @return XxfndLookupValues_V_ROVO3
     */
    public ViewObjectImpl getTRA_Option_LOV() {
        return (ViewObjectImpl) findViewObject("TRA_Option_LOV");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO1.
     * @return XxfndLookupValues_V_ROVO1
     */
    public ViewObjectImpl getTRA_Cat_LOV() {
        return (ViewObjectImpl) findViewObject("TRA_Cat_LOV");
    }


    /**
     * Container's getter for XxfndAttachment_EOView4.
     * @return XxfndAttachment_EOView4
     */
    public XxfndAttachment_EOViewImpl getSelfAttachment_EOView() {
        return (XxfndAttachment_EOViewImpl) findViewObject("SelfAttachment_EOView");
    }

    /**
     * Container's getter for XxhrDtl_Attach_VL2.
     * @return XxhrDtl_Attach_VL2
     */
    public ViewLinkImpl getXxhrDtl_Attach_VL2() {
        return (ViewLinkImpl) findViewLink("XxhrDtl_Attach_VL2");
    }

    /**
     * Container's getter for XxfndAttachment_EOView1.
     * @return XxfndAttachment_EOView1
     */
    public XxfndAttachment_EOViewImpl getOthersAttachment_EOView() {
        return (XxfndAttachment_EOViewImpl) findViewObject("OthersAttachment_EOView");
    }

    /**
     * Container's getter for XxhrDtl_Attach_VL1.
     * @return XxhrDtl_Attach_VL1
     */
    public ViewLinkImpl getXxhrDtl_Attach_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrDtl_Attach_VL1");
    }

    /**
     * Container's getter for XxfndAttachment_EOView1.
     * @return XxfndAttachment_EOView1
     */
    public XxfndAttachment_EOViewImpl getXxfndAttachment_EOView1() {
        return (XxfndAttachment_EOViewImpl) findViewObject("XxfndAttachment_EOView1");
    }

    /**
     * Container's getter for XxhrHmoMasterHdr_ROVO1.
     * @return XxhrHmoMasterHdr_ROVO1
     */
    public XxhrHmoMasterHdr_ROVOImpl getXxhrHmoMasterHdr_ROVO1() {
        return (XxhrHmoMasterHdr_ROVOImpl) findViewObject("XxhrHmoMasterHdr_ROVO1");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO1.
     * @return XxfndLookupValues_V_ROVO1
     */
    public ViewObjectImpl getTitle_LOV() {
        return (ViewObjectImpl) findViewObject("Title_LOV");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO2.
     * @return XxfndLookupValues_V_ROVO2
     */
    public ViewObjectImpl getGender_LOV() {
        return (ViewObjectImpl) findViewObject("Gender_LOV");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO1.
     * @return XxfndLookupValues_V_ROVO1
     */
    public ViewObjectImpl getOtherDependents_LOV() {
        return (ViewObjectImpl) findViewObject("OtherDependents_LOV");
    }

    /**
     * Container's getter for XxfndLookupValues_V_ROVO2.
     * @return XxfndLookupValues_V_ROVO2
     */
    public ViewObjectImpl getMaritalStatus_LOV() {
        return (ViewObjectImpl) findViewObject("MaritalStatus_LOV");
    }


    /**
     * Container's getter for XxfndLookupValues_V_ROVO1.
     * @return XxfndLookupValues_V_ROVO1
     */
    public ViewObjectImpl getXxfndLookupValues_V_ROVO() {
        return (ViewObjectImpl) findViewObject("XxfndLookupValues_V_ROVO");
    }
    
    public ArrayList getHMOCost(double p_hmo_trx_hdr_id, String p_hmo_request_date, double p_hmo_master_hdr_id,
                             String p_hmo_type, long p_person_id, String p_hmo_category, String p_hmo_option,
                             double p_hmo_plan_total, String p_dependent_type, 
                             String p_dep_dob, String p_addi_category) {
        
        System.err.println("came in try getHMOCost");
       // System.err.println("person_id ---- " + person_id);
        System.err.println("p_dep_dobe ---- " + p_dep_dob);
        //System.err.println("hmo_category ---- " + hmo_category);
        //System.err.println("hmo_option ---- " + hmo_option);

        ArrayList list = new ArrayList();
        CallableStatement st = null;
        try {
            DateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            java.util.Date reqday = inputFormat.parse(p_hmo_request_date);
            java.sql.Date reqDate = new java.sql.Date(reqday.getTime());
            java.util.Date depday = inputFormat.parse(p_dep_dob);
            java.sql.Date depDate = new java.sql.Date(depday.getTime());
            st =
                this.getDBTransaction()
                .createCallableStatement("BEGIN ? :=  xxhr_hmo_pkg.hmo_cost(?,?,?,?,?,?,?,?,?,?,?);END;", 0);

            st.registerOutParameter(1, Types.DOUBLE);
            st.setDouble(2, p_hmo_trx_hdr_id);
            st.setDate(3, reqDate);
            st.setDouble(4, p_hmo_master_hdr_id);
            st.setString(5, p_hmo_type);
            st.setLong(6, p_person_id);
            st.setString(7, p_hmo_category);
            st.setString(8, p_hmo_option);
            st.setDouble(9, p_hmo_plan_total);
            st.setString(10, p_dependent_type);
            st.setDate(11, depDate);
            st.setString(12, p_addi_category);
            st.executeUpdate();
            list.add(st.getDouble(1));
        } catch (SQLException e) {
            throw new JboException(e.getMessage());
        } catch (ParseException e) {
        } finally {
            if (st != null) {
                try {
                    st.close();
                } catch (SQLException e) {
                }
            }
        }
        return list;
    }
    

    public ArrayList dependent_details(BigDecimal hdr_id, BigDecimal person_id , String hmo_type, String hmo_category,
                                       String hmo_option) {
        //        String p_errorMessgae = null;
        //                String p_errorCode =null;
        System.err.println("came in try dependent_details");
        System.err.println("hdr_id ---- " + hdr_id);
        System.err.println("hmo_type ---- " + hmo_type);
        System.err.println("hmo_category ---- " + hmo_category);
        System.err.println("hmo_option ---- " + hmo_option);
        
        ArrayList list = new ArrayList();
        try {
           
            String stmt1 =
                "begin xxhr_hmo_pkg.copy_dependent_details(:p_new_trx_hdr_id,:p_person_id,:p_hmo_type,:p_hmo_category,:p_hmo_option,:p_return_code,:p_return_msg); end;";
            CallableStatement cst = null;
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("p_new_trx_hdr_id", hdr_id);
            cst.setObject("p_person_id", person_id);
            cst.setObject("p_hmo_type", hmo_type);
            cst.setObject("p_hmo_category", hmo_category);
            cst.setObject("p_hmo_option", hmo_option);
//            cst.setObject("p_well_id", well_id);
//            cst.setObject("p_period", period);
            cst.registerOutParameter("p_return_code", Types.VARCHAR);
            cst.registerOutParameter("p_return_msg", Types.VARCHAR);
            cst.executeUpdate();
            if (cst.getObject("p_return_code") != null) {
                System.err.println("p_return_code----- " + cst.getObject("p_return_code"));
                list.add(cst.getObject("p_return_code").toString());
            } else {
                list.add(" ");
            }
            if (cst.getObject("p_return_msg") != null) {
                System.err.println("p_return_msg------- " + cst.getObject("p_return_msg"));
                list.add(cst.getObject("p_return_msg").toString());
            } else {
                list.add(" ");
            }

        } catch (SQLException e) {
            System.err.println("came in try dependent_details catch");
            e.printStackTrace();
        }
        return list;

    }
    
    public ArrayList employee_photo_details(BigDecimal hdr_id,BigDecimal person_id , String hmo_type, String hmo_category,
                                            String hmo_option) {
            //        String p_errorMessgae = null;
            //                String p_errorCode =null;
            System.err.println("came in try employee_photo_details");
            System.err.println("person_id ---- " + person_id);
            System.err.println("hmo_type ---- " + hmo_type);
            System.err.println("hmo_category ---- " + hmo_category);
            System.err.println("hmo_option ---- " + hmo_option);
            ArrayList list = new ArrayList();
            try {
               
                String stmt1 =
                    "begin xxhr_hmo_pkg.copy_employee_photo(:p_new_trx_hdr_id,:p_person_id,:p_hmo_type,:p_hmo_category,:p_hmo_option ,:p_photo ,:p_photo_clob ,:p_return_code,:p_return_msg); end;";
                CallableStatement cst = null;
                cst = this.getDBTransaction().createCallableStatement(stmt1, 0); 
                cst.setObject("p_new_trx_hdr_id", hdr_id);
                cst.setObject("p_person_id", person_id);
                cst.setObject("p_hmo_type", hmo_type);
                cst.setObject("p_hmo_category", hmo_category);
                cst.setObject("p_hmo_option", hmo_option);
        //            cst.setObject("p_well_id", well_id);
        //            cst.setObject("p_period", period);
                cst.registerOutParameter("p_photo", Types.BLOB);
                cst.registerOutParameter("p_photo_clob", Types.CLOB);
                cst.registerOutParameter("p_return_code", Types.VARCHAR);
                cst.registerOutParameter("p_return_msg", Types.VARCHAR);
                cst.executeUpdate();
                if (cst.getObject("p_photo") != null) {
                    System.err.println("p_photo----- " + cst.getObject("p_photo"));
                    list.add(cst.getObject("p_photo"));
                } else {
                    list.add(" ");
                }
                if (cst.getObject("p_photo_clob") != null) {
                    System.err.println("p_photo_clob----- " + cst.getObject("p_photo_clob"));
                    list.add(cst.getObject("p_photo_clob"));
                } else {
                    list.add(" ");
                }
                if (cst.getObject("p_return_code") != null) {
                    System.err.println("p_return_code----- " + cst.getObject("p_return_code"));
                    list.add(cst.getObject("p_return_code").toString());
                } else {
                    list.add(" ");
                }
                if (cst.getObject("p_return_msg") != null) {
                    System.err.println("p_return_msg------- " + cst.getObject("p_return_msg"));
                    list.add(cst.getObject("p_return_msg").toString());
                } else {
                    list.add(" ");
                }

            } catch (SQLException e) {
                System.err.println("came in try copy_employee_photo catch");
                e.printStackTrace();
            }
            return list;

        }

    /**
     * Container's getter for MaximumEligibleCost_ROVO1.
     * @return MaximumEligibleCost_ROVO1
     */
    public MaximumEligibleCost_ROVOImpl getMaximumEligibleCost_ROVO() {
        return (MaximumEligibleCost_ROVOImpl) findViewObject("MaximumEligibleCost_ROVO");
    }
    
    public ArrayList getEmpHmoCost(double p_hmo_master_hdr_id,
                             String p_hmo_type, long p_person_id, String p_hmo_category, String p_hmo_option,
                             String p_emp_dob, String p_addi_category) {
        
        System.out.println("Inside Get Employee HMO Cost");
        ArrayList list = new ArrayList();
        
        System.out.println("---------getEmpHmoCost-----Entering method----------");

                System.out.println("p_hmo_master_hdr_id age---getEmpHmoCost------------------"+p_hmo_master_hdr_id+
                                   "p_hmo_category age----------getEmpHmoCost-----------"+p_hmo_category);
                System.out.println("p_hmo_type age --------getEmpHmoCost-------------"+p_hmo_type 
                      +"p_hmo_option age--------getEmpHmoCost-------------"+p_hmo_option 
                                   +"p_emp_dob age--------getEmpHmoCost-------------"+p_emp_dob
                                   +"p_addi_category age--------getEmpHmoCost-------------"+p_addi_category);
        CallableStatement st = null;
        try {
            DateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            java.util.Date depday = inputFormat.parse(p_emp_dob);
            java.sql.Date depDate = new java.sql.Date(depday.getTime());
            System.out.println("Step5-->  emp_hmo_cost Package call");
            st =
                this.getDBTransaction()
                .createCallableStatement("BEGIN ? :=  xxhr_hmo_pkg.emp_hmo_cost(?,?,?,?,?,?,?);END;", 0);
           
            st.registerOutParameter(1, Types.DOUBLE);
            st.setDouble(2, p_hmo_master_hdr_id);
            st.setString(3, p_hmo_type);
            st.setLong(4, p_person_id);
            st.setString(5, p_hmo_category);
            st.setString(6, p_hmo_option);
            st.setDate(7, depDate);
            st.setString(8, p_addi_category);
            st.executeUpdate();
            list.add(st.getDouble(1));
          

        } catch (SQLException e) {
            throw new JboException(e.getMessage());

        } catch (ParseException e) {
        } finally {
            if (st != null) {
                try {
                    st.close();
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            }
        }
        System.err.println("##list from getEmpHmoCost-->"+list);
        return list;
    }
    
    public ArrayList getEmpAgeCategory(double p_hmo_master_hdr_id, String p_hmo_type, String p_emp_dob) {

        System.out.println("---------empAgeCategory-----Entering method----------");

                System.out.println("p_hmo_type age---empAgeCategory------------------"+p_hmo_type+
                                   "p_hmo_master_hdr_id age----------empAgeCategory-----------"+p_hmo_master_hdr_id);
                System.out.println("p_hmo_type age --------empAgeCategory-------------"+p_hmo_type 
                      +"p_emp_dob age--------empAgeCategory-------------"+p_emp_dob);
        ArrayList list = new ArrayList();
        CallableStatement st = null;

        System.out.println();

        try {
            System.out.println("-----------empAgeCategory-----3----------------");

            DateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
          

            java.util.Date depday = inputFormat.parse(p_emp_dob);
            java.sql.Date empDate = new java.sql.Date(depday.getTime());
            System.out.println("Sql Date p_emp_dob ---------- " + empDate);
            System.out.println("step8--> package emp_age_category ");
            
            //Creating sql statement
            st =
                this.getDBTransaction()
                .createCallableStatement("BEGIN ? :=  xxhr_hmo_pkg.emp_age_category(?,?,?);END;", 0);


            //Register out parameter for default return value of function
            st.registerOutParameter(1, Types.VARCHAR);

            //Set IN parameter's value
            st.setDouble(2, p_hmo_master_hdr_id);
            st.setString(3, p_hmo_type);
            st.setDate(4, empDate);


            st.executeUpdate();
            list.add(st.getString(1));
            System.out.println("Output ------empAgeCategory------>" + st.getObject(1).toString());

        } catch (SQLException e) {
            throw new JboException(e.getMessage());

        } catch (ParseException e) {
        } finally {
            if (st != null) {
                try {
                    st.close();
                } catch (SQLException e) {
                    System.out.println(e.getMessage() + "---empAgeCategory----");
                }
            }
        }

        return list;
    }

    /**
     * Container's getter for SearchHmoTrxHdr_ROVO.
     * @return SearchHmoTrxHdr_ROVO
     */
    public ViewObjectImpl getSearchHmoTrxHdr_ROVO() {
        return (ViewObjectImpl) findViewObject("SearchHmoTrxHdr_ROVO");
    }

    /**
     * Container's getter for XxhrHmoMaintance_VO1.
     * @return XxhrHmoMaintance_VO1
     */
    public ViewObjectImpl getHMOMaintance_VO() {
        return (ViewObjectImpl) findViewObject("HMOMaintance_VO");
    }

    /**
     * Container's getter for XxhrHmoComplaint_VO1.
     * @return XxhrHmoComplaint_VO1
     */
    public ViewObjectImpl getHMOComplaint_VO() {
        return (ViewObjectImpl) findViewObject("HMOComplaint_VO");
    }

    /**
     * Container's getter for HMOOtherRequestDetails_ROVO1.
     * @return HMOOtherRequestDetails_ROVO1
     */
    public ViewObjectImpl getHMOOtherRequestDetails_ROVO() {
        return (ViewObjectImpl) findViewObject("HMOOtherRequestDetails_ROVO");
    }

    /**
     * Container's getter for HMOHdrRequestDetails_VL1.
     * @return HMOHdrRequestDetails_VL1
     */
    public ViewLinkImpl getHMOHdrRequestDetails_VL1() {
        return (ViewLinkImpl) findViewLink("HMOHdrRequestDetails_VL1");
    }

    /**
     * Container's getter for XxhrHmoCard_VO1.
     * @return XxhrHmoCard_VO1
     */
    public ViewObjectImpl getHMOCard_VO() {
        return (ViewObjectImpl) findViewObject("HMOCard_VO");
    }

    /**
     * Container's getter for XxfndAttachment_EOView2.
     * @return XxfndAttachment_EOView2
     */
    public XxfndAttachment_EOViewImpl getCardAttachment_Vo() {
        return (XxfndAttachment_EOViewImpl) findViewObject("CardAttachment_Vo");
    }

    /**
     * Container's getter for XxhrCard_Attach_VL1.
     * @return XxhrCard_Attach_VL1
     */
    public ViewLinkImpl getXxhrCard_Attach_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrCard_Attach_VL1");
    }

    /**
     * Container's getter for XxhrHmoReimbursement_VO1.
     * @return XxhrHmoReimbursement_VO1
     */
    public ViewObjectImpl getHMOReimbursement_VO() {
        return (ViewObjectImpl) findViewObject("HMOReimbursement_VO");
    }

    /**
     * Container's getter for XxfndAttachment_EOView2.
     * @return XxfndAttachment_EOView2
     */
    public XxfndAttachment_EOViewImpl getReimbursement_Attachment_VO() {
        return (XxfndAttachment_EOViewImpl) findViewObject("Reimbursement_Attachment_VO");
    }

    /**
     * Container's getter for XxhrReimburs_Attach_VL1.
     * @return XxhrReimburs_Attach_VL1
     */
    public ViewLinkImpl getXxhrReimburs_Attach_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrReimburs_Attach_VL1");
    }

    /**
     * Container's getter for XxhrHmoHdr_VO1.
     * @return XxhrHmoHdr_VO1
     */
    public ViewObjectImpl getNewDepHmoHdr_VO() {
        return (ViewObjectImpl) findViewObject("NewDepHmoHdr_VO");
    }

    /**
     * Container's getter for XxhrHmoDtl_VO1.
     * @return XxhrHmoDtl_VO1
     */
    public ViewObjectImpl getNewDepHmoDtl_VO() {
        return (ViewObjectImpl) findViewObject("NewDepHmoDtl_VO");
    }

    /**
     * Container's getter for XxhrHmoNewDep_VL1.
     * @return XxhrHmoNewDep_VL1
     */
    public ViewLinkImpl getXxhrHmoNewDep_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrHmoNewDep_VL1");
    }

    public ArrayList createNewDependentRequest(String hmo_ref_no) {
        System.err.println("@Enetred in createNewDependentRequest !!");
        ArrayList list = new ArrayList();
        try {
            Number hmo_ref = new Number(hmo_ref_no);
            String stmt1 = "BEGIN CREATE_NEW_DEP_REQUEST(:I_HMO_REF_NO,:O_HMO_REQ_ID,:O_ERROR_MSG); END;";
            CallableStatement st = null;
            st = this.getDBTransaction().createCallableStatement(stmt1, 0);
            st.setObject("I_HMO_REF_NO", hmo_ref);
            st.registerOutParameter("O_HMO_REQ_ID", Types.VARCHAR);
            st.registerOutParameter("O_ERROR_MSG", Types.VARCHAR);
            st.executeUpdate();
            if (st.getObject("O_HMO_REQ_ID") != null) {
                list.add(st.getObject("O_HMO_REQ_ID").toString());
            } else {
                list.add("0");
            }
            if (st.getObject("O_ERROR_MSG") != null) {
                list.add(st.getObject("O_ERROR_MSG").toString());
            } else {
                list.add("0");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.err.println("@List from createNewDependentRequest-->" + list);
        return list;
    }

    /**
     * Container's getter for XxfndAttachment_EOView2.
     * @return XxfndAttachment_EOView2
     */
    public XxfndAttachment_EOViewImpl getNewDepAttachment_VO() {
        return (XxfndAttachment_EOViewImpl) findViewObject("NewDepAttachment_VO");
    }

    /**
     * Container's getter for XxhrNewDep_Attach_VL1.
     * @return XxhrNewDep_Attach_VL1
     */
    public ViewLinkImpl getXxhrNewDep_Attach_VL1() {
        return (ViewLinkImpl) findViewLink("XxhrNewDep_Attach_VL1");
    }
    
    public String updateDeleteFlag(String hmo_ref_no, String req_type) {
        System.err.println("hmo_ref_no--"+hmo_ref_no);
        System.err.println("req_type--"+req_type);
        String msg = "E";
        try {
            Number hmo_ref = new Number(hmo_ref_no);
            String stmt1 = "BEGIN HMO_UPDATE_DELETE_FLAG(:I_HMO_REF_NO,:I_REQ_TYPE,:O_MSG); END;";
            CallableStatement st = null;
            st = this.getDBTransaction().createCallableStatement(stmt1, 0);
            st.setObject("I_HMO_REF_NO", hmo_ref);
            st.setObject("I_REQ_TYPE", req_type);
            st.registerOutParameter("O_MSG", Types.VARCHAR);
            st.executeUpdate();
            msg =  st.getObject("O_MSG")!=null ?st.getObject("O_MSG").toString() : "E";
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return msg;
    }
    

    public ArrayList copyDepDetails(String hmo_ref_no) {
        System.err.println("@Enetred in copyDepDetails !!");
        ArrayList list = new ArrayList();
        try {
            Number hmo_ref = new Number(hmo_ref_no);
            String stmt1 = "BEGIN CREATE_NEW_DEP_REQUEST_v1(:p_HMO_REF_NO,:O_HMO_REQ_ID,:O_ERROR_MSG); END;";
            CallableStatement st = null;
            st = this.getDBTransaction().createCallableStatement(stmt1, 0);
            st.setObject("p_HMO_REF_NO", hmo_ref);
            st.registerOutParameter("O_HMO_REQ_ID", Types.VARCHAR);
            st.registerOutParameter("O_ERROR_MSG", Types.VARCHAR);
            st.executeUpdate();
            if (st.getObject("O_HMO_REQ_ID") != null) {
                list.add(st.getObject("O_HMO_REQ_ID").toString());
            } else {
                list.add("0");
            }
            if (st.getObject("O_ERROR_MSG") != null) {
                list.add(st.getObject("O_ERROR_MSG").toString());
            } else {
                list.add("0");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.err.println("@List from createNewDependentRequest-->" + list);
        return list;
    }

    /**
     * Container's getter for Maxlimit_vo1.
     * @return Maxlimit_vo1
     */
    public ViewObjectImpl getMaxlimit_vo1() {
        return (ViewObjectImpl) findViewObject("Maxlimit_vo1");
    }
}
