package model.svo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 22 16:58:39 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupValue_SVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        S_No,
        Lookup_Value_Code,
        Lookup_Value_Name,
        Parent_Code;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int S_NO = AttributesEnum.S_No.index();
    public static final int LOOKUP_VALUE_CODE = AttributesEnum.Lookup_Value_Code.index();
    public static final int LOOKUP_VALUE_NAME = AttributesEnum.Lookup_Value_Name.index();
    public static final int PARENT_CODE = AttributesEnum.Parent_Code.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LookupValue_SVORowImpl() {
    }
}

