package model.svo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 23 12:33:26 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DependentClass_SVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        S_No,
        DependentClassCode,
        DependentClassName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return DependentClass_SVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return DependentClass_SVORowImpl.AttributesEnum.firstIndex() + DependentClass_SVORowImpl.AttributesEnum
                                                                                                    .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = DependentClass_SVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int S_NO = AttributesEnum.S_No.index();
    public static final int DEPENDENTCLASSCODE = AttributesEnum.DependentClassCode.index();
    public static final int DEPENDENTCLASSNAME = AttributesEnum.DependentClassName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DependentClass_SVORowImpl() {
    }
}

